# Generated by Django 5.1.2 on 2024-10-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название турнира')),
                ('date', models.DateField(verbose_name='Дата турнира')),
                ('description', models.TextField(verbose_name='Описание турнира')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tournament_images/', verbose_name='Изображение турнира')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('nickname', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('experience', models.IntegerField(verbose_name='Опыт (лет)')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('tg_link', models.URLField(verbose_name='Ссылка на Telegram')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'unique_together': {('tournament', 'nickname')},
            },
        ),
    ]
