# Generated by Django 5.1.2 on 2024-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tg_link',
            field=models.CharField(max_length=40, verbose_name='Ссылка на Telegram'),
        ),
    ]
