# Generated by Django 5.1.2 on 2024-10-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0003_alter_players_tournaments'),
        ('tournaments', '0003_alter_participant_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='tournaments_participated', to='players.players', verbose_name='Игроки'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club', verbose_name='Клуб'),
        ),
    ]
