# Generated by Django 5.1.2 on 2024-10-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_players_alter_tournament_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
    ]
