# Generated by Django 5.1.2 on 2024-10-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_remove_tournament_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='experience',
            field=models.FloatField(blank=True, null=True, verbose_name='Опыт (лет)'),
        ),
    ]
