# Generated by Django 5.1.2 on 2024-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0001_initial'),
        ('tournaments', '0003_alter_participant_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='players', to='clubs.club', verbose_name='Клубы'),
        ),
        migrations.AddField(
            model_name='players',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='players', to='tournaments.tournament', verbose_name='Турниры'),
        ),
        migrations.AlterField(
            model_name='players',
            name='experience',
            field=models.PositiveIntegerField(verbose_name='Опыт (в годах)'),
        ),
        migrations.AlterField(
            model_name='players',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='players',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
