# Generated by Django 5.1.2 on 2024-10-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_players_clubs_players_tournaments_and_more'),
        ('tournaments', '0003_alter_participant_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='participating_players', to='tournaments.tournament', verbose_name='Турниры'),
        ),
    ]
