# Generated by Django 5.1.2 on 2024-10-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_players_tournaments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='tournaments',
        ),
    ]
